name: weather_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http:
  shared_preferences:
  connectivity:
#  firebase_messaging:
  retrofit:
  json_annotation: 3.0.1
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator:
  json_serializable: 3.4.1
  build_runner: 1.10.2

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/